version: "3.9"

services:
  frontend:
    image: scqweb_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]  
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: scqweb_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      - ENV=production
